### ISSUE TITLE
애플리케이션 실행 시 hibernate ddl-auto 관련해서 질문

### ISSUE THREAD

**Issue by Brightbong92** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-16#2]
실행했을때 ORM에서 auto ddl시 아래와 같은 문법 에러가 발생하는데요.
원인은 performance 테이블 DDL 생성시 is_reverse에 varchar타입의 바이트가 설정안되는게 원인으로 파악됩니다.
columnDefinition에 바이트를 직접 지정해주니 DDL이 올바르게 생성이 됩니다.

name의 경우 바이트가 자동으로 255로 잡히는데요. 이 방법으로 해결하는게 맞는건지 궁금해 문의남깁니다.

```
// AS-IS
// Performance Entity
...
   @Column(nullable = false, name = "is_reserve", columnDefinition = "varchar default 'disable'")
    private String isReserve;
```

```
// TO-BE
// Performance Entity
@Column(nullable = false, name = "is_reserve", columnDefinition = "varchar(255) default 'disable'")
    private String isReserve;
```

# ERROR
```
...
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "
    create table performance (
        price integer not null,
        round integer not null,
        start_date date not null,
        type integer not null,
        id BINARY(16) not null,
        is_reserve varchar default 'disable' not null,
        name varchar(255) not null,
        primary key (id)
    ) engine=InnoDB" via JDBC [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'default 'disable' not null,
        name varchar(255) not null,
        primary ' at line 7
...

```
![스크린샷 2024-01-19 오후 3 58 52](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/51194127/fcab8a1f-bce3-464a-a4fa-3394d02ec0ad)

![스크린샷 2024-01-19 오후 2 54 58](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/51194127/eb4dd8ec-7d4a-4cfb-80eb-1d9f6e015ceb)

# SOLVE
![스크린샷 2024-01-19 오후 4 13 25](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/51194127/23d97401-444c-499d-bce5-a127d7f2b44e)

**Comment by jinho-yoo-jack** [comment]
앗..! 맞습니다! 제가 수정하고 해당하는 부분을 Commit 하지 않은 것 같네요; 제 실수 입니다...
@Brightbong92  현봉님 덕분에 다른 분들이 고생하지 않을 것 같습니다.
너무 좋은 질문 주셔서 감사합니다.
