### ISSUE TITLE
과제 제출하고 싶은데 remote: Permission to 로 올리지 못하고 있습니다

### ISSUE THREAD

**Issue by jsoyun** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-16#20]
(덕분에 해결했습니다!)
git clone해왔는데 추가 설정이 필요한 걸까요?😂
<img width="740" alt="image" src="https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/89512178/e8e16461-360c-47ff-827b-74a8be195b47">

**Comment by bbbbooo** [comment]
저도 그런 문제가 있었는데 간단한거였더라구요..! 대신 코멘트 남깁니다!!

단순하개 클론만으로는 메인 레포에 권한이 없어서 푸시가 안되고 포크를 받아야합니다!

1. 본인의 레포지토리로 포크 받기
2. 클론 받았던 프로젝트의 원격 레포지토리 설정을 포크 받은 레포지토리로 설정
3. 이제 푸시하시면 pr을 올리실 수 있을거에요

**Comment by jinho-yoo-jack** [comment]
@bbbbooo 친절한 답변 너무 감사드립니당 ㅎㅎ
@jsoyun  좀 더 상세한 내용이 필요하시다면 아래의 링크를 통해서 확인해주세요
URL: https://chanhuiseok.github.io/posts/git-3/

**Comment by jsoyun** [comment]
상세한 설명 감사합니다~! 덕분에 올렸습니다!!
