### ISSUE TITLE
도커 설정시 디렉토리 경로 생성 오류 관련해 질문드립니다.

### ISSUE THREAD

**Issue by seongchanhwang** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-16#24]
-
User@DESKTOP-BND7KCB MINGW64 /d/challenge/wanted-preonboarding-challenge-backend-16 (master)
$ docker-compose up -d
[+] Running 0/1
 - Container wanted-preonboarding-challenge-backend-16-mysql-1  Starting                                                          0.2s
Error response from daemon: error while creating mount source path '/Users/black/dev/mysql_docker/data': mkdir /Users: file exists

안녕하세요 
/Users 디렉토리를 생성할 때 오류가 발생한다는것 같은데 해결방법을 알 수 있을까요 ??

**Comment by jinho-yoo-jack** [comment]
@seongchanhwang 해당 디렉토리는 제 Mac 환경에 맞게 설정되어 있는 부분이라서 수정을 하셔야 합니다!!

**Comment by seongchanhwang** [comment]
답변 감사합니다. 
도커 컨테이의 mySQL은 잘 연결 된 것 같은데 
프로젝트 띄울때 Access denied for user 'wanted'@'172.18.0.1' (using password: YES) 오류가 발생합니다. 
![image](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/46668449/9377c7c5-b0c7-4088-83ca-79d91e730106)

혹시 제가 어떤 설정을 잘못했는지 알 수 있을까요 ?? 

**docker-compse.yml** 
![image](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/46668449/663bdb9c-23b1-4843-85f5-547e73a791fe)




![image](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/46668449/2a86ba7b-d5d1-4708-87d0-a1245f1523e2)


![image](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/46668449/7e163a6d-156e-40a1-aaf1-b82d41122c2d)

**Comment by shandyCho** [comment]
docker 컨테이너 내에 mysql 계정이 제대로 생성되었는지, database가 생성되었는지 확인 해보셨나요?

**Comment by jinho-yoo-jack** [comment]
@seongchanhwang MySQL 실행은 잘 되었으나, 접속 권한이 없어서 그런거 같아요!
1. Docker Container CLI로 접속 후,
2. wanted 계정으로 접근 후, 권한 설정하면 될 거에요!
참고 URL도 보시면 이해 하실 수 있으실거에요!
참고 URL:
https://medium.com/tech-learn-share/docker-mysql-access-denied-for-user-172-17-0-1-using-password-yes-c5eadad582d3

**Comment by seongchanhwang** [comment]
감사합니다! 권한 때문이었나보네요 잘 해결되었습니다
