### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by ssac17** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-16#3]
주어진 환경은 jpa가 ddl-auto가 none이라 docker로 db 실행할때 resources에 있는 sql 로 테이블이 생성되는데요. 그러면 만약 조인을 하게 될 경우 sql 테이블 정보를 수정해서 해야하는지 아니면 sql 파일은 참고만 하고 엔티티 클래스를 수정하면서 해야하나요?

**Comment by jinho-yoo-jack** [comment]
@ssac17 어떤 방법으로 하든 상관은 없을 것 같습니다! 다만, 한가지 의견을 제시한다면! entity로 하는 방법도 해보시고! resource 경로 하위에 있는 파일로 해보시고 각각의 장단점을 비교해보고 실 환경에서는 무엇이 더 좋을지 고민해보는건 어떨까요?

**Comment by ssac17** [comment]
넵 답변감사합니다^^
