### ISSUE TITLE
jdk, IDE 설정

### ISSUE THREAD

**Issue by kmkim0713** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-16#33]
안녕하세요.. 소스를 내려받고나서 실행을 실행시켰는데요.

에러없이 구동이 되었는데, 

message 부분이 빨간색으로 에러가 뜨는데,, 실행에는 문제가 없습니다.

ResponseHandler.java도 건드린게 따로 없습니다..

다른분이 이슈 올려주시긴 했는데, bulid.gradle.kts 파일쪽도 빨간줄이 계속 뜨더라구요. 
"Reload Gradle Project"를 수행해도 여전하네요..

![스크린샷 2024-02-03 오후 11 49 20](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/157942767/45f01c47-bf9d-4cfd-8c3f-f8dedfc3d6b8)

![스크린샷 2024-02-03 오후 11 52 39](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/157942767/2eca822d-3783-4c02-8879-f7bf9757c122)
)

![스크린샷 2024-02-03 오후 11 51 55](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/157942767/cfa62178-6168-496c-80b3-6e6762d1bc6a)

**Comment by shandyCho** [comment]
첫번째 에러는 Builder 어노테이션을 IDE에서 인식하지 못해서 발생하는 것이 아닐까 생각합니다. 이에 대한 해결 방법은  https://hyunalee.tistory.com/97 를 참고해보시면 될 것 같습니다.

+추가: 두번째 에러랑 연동되어 생기는 에러 같습니다. JAVA_HOME 경로가 Java 17 JDK 경로인지, 아니라면 임시방편으로 gradle.properites 파일을 생성하셔서 org.gradle.java.home=Java 17 JDK 경로 를 입력해주신 뒤 Gradle을 다시 로드해보시면 될 것 같습니다. 

![스크린샷 2024-02-04 011107](https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/assets/129934364/465bb59c-117c-49e4-9136-c0c3ccec8b31)


두번째 에러는 Setting-Build, Execution, Deployment-Gradle에서 Gradle 설정들 확인해보셔야 할 것 같습니다. 확인 해보셨다면 하단의 링크 참고해보시면 될 것 같습니다
https://codingbuza.tistory.com/entry/%EC%9D%B8%ED%94%84%EB%9F%B0-Spring-%EC%9E%85%EB%AC%B8-JDK-17-isnt-compatible-with-Gradle-811-Please-fix-JAVAHOME-environment-variable-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0

**Comment by jinho-yoo-jack** [comment]
@kmkim0713 JDK 버전 문제로 판단이 됩니다. 위에서 @HoomanHoo 님께서 이야기 해주신대로 수정해보시면 정상적으로 빨간 줄이 사라질 겁니다!
@HoomanHoo  감자합니다 ㅎㅎ

**Comment by kmkim0713** [comment]
- homebrew로 java 17을 재설치
- 환경변수 설정 확인 JAVA_HOME
- 인텔리제이 프로젝트 SDK설정 확인
- 인텔리제이 Preferences의 Gradle 설정 변경
- gradle.properties 추가

3시간정도 끙끙댔는데 ,, 결국엔 안되네요.. 우선 수업을 들어야겠어요 ..

**Comment by seol-park** [comment]
https://pamyferret.tistory.com/62 이 글 참고하셔서 out 폴더 지우시고 빌드 바꿔보시는 것도 방법일 것 같아요! 다른 분 이걸로 도와드렸어요 방금ㅎㅎ

**Comment by kmkim0713** [comment]
@ParkSeolDev 
답변 감사드립니다.

찾아보니 out 폴더는 Intelij IDEA 빌드 설정시에 생성되는 것 같은데요..저는 빌드 후에도 out 폴더가 생성되거나 하질 않아서 삭제할 것이 없습니다 ..ㅠ 어렵네요.

**Comment by seol-park** [comment]
@kmkim0713 호옥시 https://blog.powerumc.kr/455 이건요? 자바 버전 다른거 쓰시다가 바꾸셨져?

**Comment by kmkim0713** [comment]
@ParkSeolDev 
댓글주셔서 감사합니다..

네 맞습니다 ㅠ.. 저거대로 디렉토리를 날리고 재빌드를 했는데 쓰읍 ... 안되네요

**Comment by kmkim0713** [comment]
혹시나 같은 이슈를 만나신 분이 계실까봐 마지막으로 댓글 남깁니다.
해당 이슈는 인텔리제이 버전 문제로 결론 지어야 할 것 같습니다.
VSC 설치 후, Spring boot 기동을 위한 플러그인 추가하여 실행시키니 문제없이 실행되었습니다.


개발환경: 인텔리제이 얼티밋 2021.3 버전 (회사 라이센스 사용, 버전 업데이트 불가한 상황)
OS: Mac
java version: openjdk17 (brew)
이슈: _Java 17에 대한 기본 지원은 IntelliJ IDEA 2021.2.1 에서 제공_
참고: https://blog.jetbrains.com/idea/2021/09/java-17-and-intellij-idea/
