### ISSUE TITLE
application.yml 내 한글 깨짐

### ISSUE THREAD

**Issue by roeniss** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-16#4]
https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/blob/master/src/main/resources/application.yml 파일이 ISO-8859-1 이슈로 한글이 깨진채 커밋된 것 같습니다. 마이너한 부분이지만, 원래 적혀있던 주석이 궁금합니다.

**Comment by jinho-yoo-jack** [comment]
@roeniss 한글 주석이 안깨짐 컨피그로 재커밋했습니다!
확인 바랍니다.
CM URL - https://github.com/jinho-yoo-jack/wanted-preonboarding-challenge-backend-16/commit/f59987ddceb762139d2c739e808d29718b3ca1b2
