### ISSUE TITLE
JPA 연관관계 설정 관련

### ISSUE THREAD

**Issue by CheorHyeon** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-16#6]
안녕하세요 주어진 코드에서 연관관계 없이 필드명으로 구성된 엔티티가 있는 것으로 파악했습니다.

- `performanceId`의 UUID

혹시 이러한 요소들을 연관관계를 맺고 기능을 구현해도 될까요? 아니면 관계를 맺지 않고 해야하나요?

-----

뭔가 연관 줘보려다가 기능 구현하면 터질수도 있어 일단은 그냥 가보도록 하겠습니다.. 연관 어렵네요 ㅜ

**Comment by jinho-yoo-jack** [comment]
@CheorHyeon 연관관계(JOIN)는 무조건 사용하셔야 합니다! ㅎㅎㅎ
어려움이 있겠지만, 화이팅!

**Comment by CheorHyeon** [comment]
@jinho-yoo-jack 아 답변 감사합니다. 구조를 그대로 두고 기능만 하는 것으로 생각해서 바꿔도 될까 고민했는데 바꿔보긴 해야겠네요 :)
열심히 해보겠습니다! 혹시 ddl-auto 설정 등을 바꿔서 JPA Entity를 활용하여 해결해도 될까요? 사실 프로젝트를 create나 update로 하고 Entity만 바꿔주고 그냥 돌려봐서 스키마 정의하고 좀 은근 헷깔리네요 ㅜㅜ
최대한 해보겠지만 정 못하면 그냥 Entity로만 해볼까 고민도 있습니다 ㅠ

**Comment by jinho-yoo-jack** [comment]
@CheorHyeon 익숙한 방법으로 먼저 해보시고, 새로운 방식도 해보시면 어떨까요?
각각의 방법은 장단점이 있으니깐요!

**Comment by CheorHyeon** [comment]
@jinho-yoo-jack 답변 주셔서 감사합니다! 고민해보고 과제 진행할게요! 추가 문의사항 있으면 남기겠습니다 !!
아 혹시 그 문제에 주어지지 않은 내용은 자율일까요? 할인 정책 등(나이 필드를 추가로 둬서 65세 이상이면 할인 적용 등)과 같은 것이요!

**Comment by jinho-yoo-jack** [comment]
@CheorHyeon 넵넵! 할인정책 적용은 자유입니다! 다만, 현실 세계의 할인 정책과 유사하게 설계하면 좋을 것 같습니다!!
