### ISSUE TITLE
Request Message 질문

### ISSUE THREAD

**Issue by bombo-dev** [jinho-yoo-jack/wanted-preonboarding-challenge-backend-16#7]
Request Message 같은 경우에는 http로 통신한다고 가정하고 작성해야하나요?
혹은 따로 콘솔을 이용한 input를 만들어주어야 하나요?

**Comment by jinho-yoo-jack** [comment]
@bombo-dev 콘솔은 따로 제공되지 않고, HTTP통신한다고 가정하고 진행하시면 좋을 것 같습니다.
